services:
  backend:
    build: ./server
    container_name: node_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongodb:27017/userdb
    volumes:
      - ./server:/app
      - node_modules:/app/node_modules
    networks:
      - app-network

  mongodb:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./client
    container_name: react_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - frontend:/app/node_modules  
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network  
    command: ["npm", "run", "dev", "--", "--host"]  

volumes:
  mongo-data:
  node_modules:
  frontend:

networks:
  app-network:
